//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PretvoriKverijaMakroaVoVBA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.sql")]
        public string VID_NA_FAJL {
            get {
                return ((string)(this["VID_NA_FAJL"]));
            }
            set {
                this["VID_NA_FAJL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VOI60_IT1_soopstenie.bas")]
        public string IME_NA_IZVEZEN_FAJL {
            get {
                return ((string)(this["IME_NA_IZVEZEN_FAJL"]));
            }
            set {
                this["IME_NA_IZVEZEN_FAJL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imeXLSFajl.xls")]
        public string IME_NA_IZVEZEN_EKSEL_FAJL {
            get {
                return ((string)(this["IME_NA_IZVEZEN_EKSEL_FAJL"]));
            }
            set {
                this["IME_NA_IZVEZEN_EKSEL_FAJL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool dodajZaIzvozVoEksel {
            get {
                return ((bool)(this["dodajZaIzvozVoEksel"]));
            }
            set {
                this["dodajZaIzvozVoEksel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrimerKverija")]
        public string PATEKA_IZVEZEN_EKSEL_FAJl {
            get {
                return ((string)(this["PATEKA_IZVEZEN_EKSEL_FAJl"]));
            }
            set {
                this["PATEKA_IZVEZEN_EKSEL_FAJl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PrimerKverija")]
        public string SQL_KVERIJA_PAPKA {
            get {
                return ((string)(this["SQL_KVERIJA_PAPKA"]));
            }
            set {
                this["SQL_KVERIJA_PAPKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MakroaKverijaPrimeri")]
        public string VBA_MAKROA_PAPKA {
            get {
                return ((string)(this["VBA_MAKROA_PAPKA"]));
            }
            set {
                this["VBA_MAKROA_PAPKA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*.bas")]
        public string VBA_MAKRO_VID_FAJL {
            get {
                return ((string)(this["VBA_MAKRO_VID_FAJL"]));
            }
            set {
                this["VBA_MAKRO_VID_FAJL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>Q_M10|TabelaKveriM10|1</string>
  <string>Q_M1|TabelaKveriM1|1</string>
  <string>Q_M2|TabelaKveriM2|1</string>
  <string>Q_M3|TabelaKveriM3|1</string>
  <string>Q_M4|TabelaKveriM4|1</string>
  <string>Q_M5|TabelaKveriM5|1</string>
  <string>Q_M6|TabelaKveriM6|1</string>
  <string>Q_M7|TabelaKveriM7|1</string>
  <string>Q_M8|TabelaKveriM8|1</string>
  <string>Q_M9|TabelaKveriM9|1</string>
  <string>TabelaVnes|TabelaVnes|0</string>
  <string>TabelaVnes2|TabelaVnes|0</string>
  <string>TabelaAdresar|TabelaAdresar|0</string>
  <string>TabelaAdresar1|TabelaAdresar|0</string>
  <string>Tgodisnik_1|TabelaGodishnik|1</string>
  <string>Tgodisnik_4|TabelaGodishnik4|1</string>
  <string>Tgodisnik_7|TabelaGodishnik7|1</string>
  <string>Tpol|TabelaPol|1</string>
  <string>RZSVNESI_T_KD_SV50A_2009|TabelaVnesSV50|0</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection iminijaTabeli {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["iminijaTabeli"]));
            }
            set {
                this["iminijaTabeli"] = value;
            }
        }
    }
}
